import arcade

SCREEN_WIDTH = 480
SCREEN_HEIGHT = 700
SCREEN_TITLE = '战争飞机雷霆'
FPS = 60

PLAYER_COLOR = arcade.color.CYAN
ENEMY_COLOR = arcade.color.RED
BULLET_COLOR = arcade.color.YELLOW
BG_COLOR = arcade.color.BLACK

PLAYER_SPEED = 5
BULLET_SPEED = 10
ENEMY_SPEED = 3
ENEMY_SPAWN_INTERVAL = 1.5
BULLET_COOLDOWN = 0.15

PLAYER_MAX_HEALTH = 3
SCORE_PER_ENEMY = 100
LEVEL_UP_SCORE = 1000

# Boss相关
BOSS_WIDTH = 60
BOSS_HEIGHT = 50
BOSS_SPEED = 2
BOSS_HEALTH = 10
BOSS_SCORE = 500
BOSS_SPAWN_INTERVAL = 5  # 波次
ENEMY_BULLET_SPEED = 5
ENEMY_BULLET_COOLDOWN = 1.5
